---
title: "Pretend Dataset 1"
format: html
---

## Name and affiliation of person filling out this form

test

## Primary Contact

test

## Secondary Contact

test

## Indicator Name (as listed in the ESR report)

Commercial landings

## Category (Which group is this indicator associated with?)

Risks to meeting fishery management objectives

## Family (Which group is this indicator associated with?)

Bycatch reduction

## Data Description

This is a pretend dataset.

## Data Type

Non-automated data access

## Public Availability

Source data are NOT publicly available.

## Accessibility and Constraints

Need to ask someone in Narnia.

## Methods for accessing and preparing data

Please be as detailed as possible. If the data are available in an online repository, please include the website link.

## Name of R script used to access and manipulate dataset

data1.R

## Key figures

Standard time series plot

## Interpretation

Proceed as though this were a short summary of a typical discussion section in a paper.

## Spatial Scale

Narnia

## Temporal Scale

Annual

## Data Limitations

The data do not exist

## Define Variables

| Name | Definition | Units |
|------------------------|------------------------|------------------------|
| Ex: 1) | NA | NA |
| piscivore_biomass; Definition: Biomass of piscivores; Units: kg tow\^-1. 2) | NA | NA |
| forage_biomass; Definition: Biomass of forage fish; Units: kg tow\^-1. | NA | NA |

## Key references

Ex. Surface North Atlantic MOM5-TOPAZ outputs derived from a regular hindcast and a robust diagnostic simulation experiment from 1980-01-01 to 2017-12-31 (NCEI Accession 0283628). NOAA National Centers for Environmental Information. Dataset. https://www.ncei.noaa.gov/archive/accession/0283628. Accessed 2023-02-19.

## Data Contributors

Ex: Carissa Gervasi, Mandy Karnauskas.
