name: ESR - Catalog Submission
description: Use this issue template to submit catalog information for the Ecosystem Status Reports.
title: "[Submission]: "
labels: ["submission"]
assignees: "CarissaGervasi-NOAA"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to an ESR report! Please reach out to carissa.gervasi@noaa.gov with any questions or concerns.
  - type: input
    id: contact1
    attributes:
      label: Primary Contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@noaa.gov
    validations:
      required: true
  - type: input
    id: contact2
    attributes:
      label: Secondary Contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@noaa.gov
    validations:
      required: false
  - type: input
    id: data_name
    attributes:
      label: Data Name (This will be the displayed title in Catalog)
      description: Enter the name of the data set.
      placeholder: Ex. Gulf of Mexico Annual Sea Surface Temperature
    validations:
      required: true
      
  - type: checkboxes
    id: indicator_name
    attributes:
      label: Indicator Name (as listed in the ESR reports)
      description: Please check the indicator this dataset is associated with.
      options:
        - label: Degree heating weeks
        - label: Ocean acidification
        - label: Hurricane activity
        - label: Turbidity
        - label: Sea surface temperature
        - label: Marine debris
        - label: Identified point source pollution sites
        - label: Primary productivity via ocean color
        - label: Coastal development
        - label: Number of major earthquakes
        - label: Market disturbances
        - label: Sargassum inundation
        - label: Tourism (hotel occupancy)
        - label: Population
        - label: Abundance of economically important fish
        - label: Abundance of commercial fish based on TCRMP and PRCRMP
        - label: Slope of the size spectrum based on TCRMP and PRCRMP
        - label: Landings 
        - label: Pelagic:demersal ratio
        - label: Lmax indicator
        - label: Total landings 
        - label: Percent revenues by species group
        - label: Number of trips 
        - label: Ocean economy 
        - label: GDP
        - label: Unemployment
        - label: Gini coefficient
        - label: Fishing community engagement and reliance
        - label: Recreational landings
        - label: Commercial engagement
        - label: Changes in gear type 
        - label: Number of seasonal closures implemented
        - label: Number of education/outreach events
        - label: Number of enforcement actions
        - label: Percent coral cover 
        - label: Coral species diversity 
    validations:
      required: true
      
  - type: checkboxes
    id: group_name
    attributes:
      label: Category (Which group is this indicator associated with?)
      description: Please check the group that applies to your indicator.
      options:
        - label: Tracking performance toward fishery management objectives
        - label: Risks to meeting fishery management objectives
    validations:
      required: true
        
  - type: checkboxes
    id: family_name
    attributes:
      label: Family (Which group is this indicator associated with?)
      description: Please check the group(s) that could apply to your indicator.
      options:
        - label: Oceanographic
        - label: Habitat
        - label: Lower trophic levels
        - label: Megafauna
        - label: Social
        - label: Economic
    validations:
      required: true
 
  - type: textarea
    id: data_description
    attributes:
      label: Data Description
      description: Briefly describe the data set.
      value: "Ex: The data presented here are the degree heating weeks (DHW) for Puerto Rico and the US Virgin Islands Daily 5km Regional Virtual Stations."
    validations:
      required: true
  - type: textarea
    id: indicator_intro
    attributes:
      label: Introduction to Indicator (Please explain your indicator)
      description: Please introduce the indicator within an appropriate context.
      value: "Proceed as though this were a short summary of a typical introduction section in a paper."
    validations:
      required: false
  - type: textarea
    id: indicator_results
    attributes:
      label: Key Results and Visualization
      description: Please describe the results and/or visualizations of this indicator.
      value: "Proceed as though this were a short summary of a typical results section in a paper."
    validations:
      required: false
  - type: textarea
    id: indicator_implications
    attributes:
      label: Implications
      description: Please describe the implications of this indicator.
      value: "Proceed as though this were a short summary of a typical discussion section in a paper."
    validations:
      required: false
  - type: input
    id: spatial_scale
    attributes:
      label: Spatial Scale
      description: Please briefly describe the spatial scale of the indicator.
      placeholder: ex. by EPU and full shelf.
    validations:
      required: false
  - type: input
    id: temporal_scale
    attributes:
      label: Temporal Scale
      description: Please briefly describe the temporal scale of the indicator.
      placeholder: ex. Spring (January-June), Fall (July-December), Annual.
    validations:
      required: false  
  - type: input
    id: data_limitations
    attributes:
      label: Data Limitations
      description: Please briefly describe any important limitations of the data.
      placeholder: "Provide a short summary of the key limitations and how they impact the indicator"    
    validations:
      required: false    
  - type: checkboxes
    id: synthesis_theme
    attributes:
      label: Synthesis Theme
      description: Please check the synthesis theme(s) that could apply to your indicator.
      options:
        - label: Multiple System Drivers
        - label: Regime Shifts
        - label: Ecosystem Reorganization
    validations:
      required: false
  - type: textarea
    id: define_variables
    attributes:
      label: Define Variables
      description: Provide definitions for all variable names with units.
      value: "Ex: 1) Name: piscivore_biomass; Definition: Biomass of piscivores; Units: kg tow^-1. 2) Name: forage_biomass; Definition: Biomass of forage fish; Units: kg tow^-1."
    validations:
      required: true
  - type: checkboxes
    id: indicator_category
    attributes:
      label: Indicator Category
      description: Select one or more categories that apply to your data set.
      options:
        - label: Published Methods
        - label: Extensive analysis, not yet published
        - label: Syntheses of published information
        - label: Database pull
        - label: Database pull with analysis
        - label: Other
          required: false
  - type: input
    id: other_indicator_category
    attributes:
      label: If other, please specify indicator category
      description: If you selected Other above, please specify a new indicator category.
      placeholder: Indicator category other than those above.
    validations:
      required: false
  - type: textarea
    id: data_contributors
    attributes:
      label: Data Contributors
      description: Enter the names of all contributing persons.
      value: "Ex: Brandon Beltz, Sarah Gaichas and Sean Lucey."
    validations:
      required: true
  - type: input
    id: point_contact
    attributes:
      label: Point(s) of Contact
      description: Enter name(s) and email(s) for point(s) of contact.
      placeholder: Ex. Brandon Beltz (brandon.beltz@noaa.gov)
    validations:
      required: true
      
      
  - type: input
    id: affiliation
    attributes:
      label: Affiliation
      description: Enter the name of your affiliation.
      placeholder: Ex. NEFSC, GARFO, SMAST, MAFSC etc.
    validations:
      required: true
      
      
      
  - type: dropdown
    id: public_availability
    attributes:
      label: Public Availability
      description: State public availability of source data for this indicator.
      multiple: false
      options:
        - Source data are publicly available.
        - Source data are NOT publicly available.
    validations:
      required: true
  - type: input
    id: accessibility
    attributes:
      label: Accessibility and Constraints
      description: If source data are NOT publicly available, what are the procedures for accessing the data?
      placeholder: Ex. Please email your.email@noaa.gov for further information and queries of X indicator source data.
    validations:
      required: false